-- MySQL Script generated by MySQL Workbench
-- Thu May 28 15:54:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bddLocker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bddLocker` ;

-- -----------------------------------------------------
-- Schema bddLocker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bddLocker` DEFAULT CHARACTER SET utf8 ;
USE `bddLocker` ;

-- -----------------------------------------------------
-- Table `bddLocker`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`Clients` ;

CREATE TABLE IF NOT EXISTS `bddLocker`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(25) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `email` VARCHAR(70) NULL,
  `pseudo` VARCHAR(20) NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddLocker`.`Livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`Livreur` ;

CREATE TABLE IF NOT EXISTS `bddLocker`.`Livreur` (
  `idLivreur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idLivreur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddLocker`.`Locker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`Locker` ;

CREATE TABLE IF NOT EXISTS `bddLocker`.`Locker` (
  `idLocker` INT NOT NULL,
  `adresse` VARCHAR(100) NULL,
  PRIMARY KEY (`idLocker`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bddLocker`.`TailleCasier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`TailleCasier`;

CREATE TABLE IF NOT EXISTS `bddLocker`.`TailleCasier` (
  `idTaille` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `longueur` FLOAT NOT NULL,
  `largeur` FLOAT NOT NULL,
  `hauteur` FLOAT NOT NULL,
  PRIMARY KEY (`idTaille`)
  
)
ENGINE = InnoDB;

INSERT INTO `bddLocker`.`TailleCasier`
(`nom`, `longueur`, `largeur`, `hauteur`)
VALUES
('Petit', 20, 20, 20),
('Moyen', 40, 30, 30),
('Grand', 60, 40, 40);

-- -----------------------------------------------------
-- Table `bddLocker`.`Casier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`Casier` ;

CREATE TABLE IF NOT EXISTS `bddLocker`.`Casier` (
  `idCasier` INT NOT NULL,
  `TailleCasier_idTaille` INT NOT NULL,
  `num_casier` VARCHAR(45) NULL,
  `Locker_idLocker` INT NOT NULL,

  PRIMARY KEY (`idCasier`),

  INDEX `fk_Casier_Locker1_idx` (`Locker_idLocker` ASC),
  INDEX `fk_Casier_Taille_idx` (`TailleCasier_idTaille` ASC),

  CONSTRAINT `fk_Casier_Locker1`
    FOREIGN KEY (`Locker_idLocker`)
    REFERENCES `bddLocker`.`Locker` (`idLocker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Casier_Taille`
    FOREIGN KEY (`TailleCasier_idTaille`)
    REFERENCES `bddLocker`.`TailleCasier` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bddLocker`.`Colis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddLocker`.`Colis` ;

CREATE TABLE IF NOT EXISTS `bddLocker`.`Colis` (
  `idColis` INT NOT NULL,
  `num_colis` INT NULL,
  `longueur` FLOAT NULL,
  `largeur` FLOAT NULL,
  `hauteur` FLOAT NULL,
  `Livreur_idLivreur` INT NOT NULL,
  `Casier_idCasier` INT NOT NULL,
  `Clients_idExpediteur` INT NOT NULL,
  `Clients_idDestinataire` INT NOT NULL,
  `destinataire` VARCHAR(255) NULL,
  PRIMARY KEY (`idColis`),
  INDEX `fk_Colis_Livreur1_idx` (`Livreur_idLivreur` ASC) ,
  INDEX `fk_Colis_Casier1_idx` (`Casier_idCasier` ASC) ,
  INDEX `fk_Colis_Clients1_idx` (`Clients_idExpediteur` ASC) ,
  INDEX `fk_Colis_Clients2_idx` (`Clients_idDestinataire` ASC) ,
  CONSTRAINT `fk_Colis_Livreur1`
    FOREIGN KEY (`Livreur_idLivreur`)
    REFERENCES `bddLocker`.`Livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Casier1`
    FOREIGN KEY (`Casier_idCasier`)
    REFERENCES `bddLocker`.`Casier` (`idCasier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Clients1`
    FOREIGN KEY (`Clients_idExpediteur`)
    REFERENCES `bddLocker`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Clients2`
    FOREIGN KEY (`Clients_idDestinataire`)
    REFERENCES `bddLocker`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
