-- MySQL Script generated by MySQL Workbench
-- Tue Jun  9 16:49:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bddlocker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bddlocker` ;

-- -----------------------------------------------------
-- Schema bddlocker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bddlocker` DEFAULT CHARACTER SET utf8 ;
USE `bddlocker` ;

-- -----------------------------------------------------
-- Table `bddlocker`.`locker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`locker` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`locker` (
  `idLocker` INT(11) NOT NULL,
  `adresse` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idLocker`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddlocker`.`taillecasier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`taillecasier` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`taillecasier` (
  `idTaille` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `longueur` FLOAT NOT NULL,
  `largeur` FLOAT NOT NULL,
  `hauteur` FLOAT NOT NULL,
  PRIMARY KEY (`idTaille`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddlocker`.`casier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`casier` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`casier` (
  `idCasier` INT(11) NOT NULL,
  `TailleCasier_idTaille` INT(11) NOT NULL,
  `num_casier` VARCHAR(45) NULL DEFAULT NULL,
  `Locker_idLocker` INT(11) NOT NULL,
  PRIMARY KEY (`idCasier`),
  INDEX `fk_Casier_Locker1_idx` (`Locker_idLocker` ASC) ,
  INDEX `fk_Casier_Taille_idx` (`TailleCasier_idTaille` ASC) ,
  CONSTRAINT `fk_Casier_Locker1`
    FOREIGN KEY (`Locker_idLocker`)
    REFERENCES `bddlocker`.`locker` (`idLocker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Casier_Taille`
    FOREIGN KEY (`TailleCasier_idTaille`)
    REFERENCES `bddlocker`.`taillecasier` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddlocker`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`clients` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`clients` (
  `idClients` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(25) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `mdp` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(70) NULL DEFAULT NULL,
  `pseudo` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddlocker`.`livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`livreur` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`livreur` (
  `idLivreur` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `mdp` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`idLivreur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddlocker`.`colis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bddlocker`.`colis` ;

CREATE TABLE IF NOT EXISTS `bddlocker`.`colis` (
  `idColis` INT(11) NOT NULL,
  `num_colis` INT(11) NULL DEFAULT NULL,
  `longueur` FLOAT NULL DEFAULT NULL,
  `largeur` FLOAT NULL DEFAULT NULL,
  `hauteur` FLOAT NULL DEFAULT NULL,
  `Livreur_idLivreur` INT(11) NOT NULL,
  `Casier_idCasier` INT(11) NOT NULL,
  `Clients_idExpediteur` INT(11) NOT NULL,
  `Clients_idDestinataire` INT(11) NOT NULL,
  `destinataire` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idColis`),
  INDEX `fk_Colis_Livreur1_idx` (`Livreur_idLivreur` ASC) ,
  INDEX `fk_Colis_Casier1_idx` (`Casier_idCasier` ASC) ,
  INDEX `fk_Colis_Clients1_idx` (`Clients_idExpediteur` ASC) ,
  INDEX `fk_Colis_Clients2_idx` (`Clients_idDestinataire` ASC) ,
  CONSTRAINT `fk_Colis_Casier1`
    FOREIGN KEY (`Casier_idCasier`)
    REFERENCES `bddlocker`.`casier` (`idCasier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Clients1`
    FOREIGN KEY (`Clients_idExpediteur`)
    REFERENCES `bddlocker`.`clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Clients2`
    FOREIGN KEY (`Clients_idDestinataire`)
    REFERENCES `bddlocker`.`clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colis_Livreur1`
    FOREIGN KEY (`Livreur_idLivreur`)
    REFERENCES `bddlocker`.`livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
